# SPDX-FileCopyrightText: 2024 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-FileContributor: Ben Ford <ben.ford@kdab.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
msrv = "1.77.2"
