# SPDX-FileCopyrightText: 2022 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-FileContributor: Andrew Hayzen <andrew.hayzen@kdab.com>
# SPDX-FileContributor: Gerhard de Clercq <gerhard.declercq@kdab.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

# ANCHOR: book_cargo_toml_no_cmake
[package]
name = "qml-minimal-no-cmake"
version = "0.1.0"
authors = [
  "Andrew Hayzen <andrew.hayzen@kdab.com>",
  "Be Wilson <be.wilson@kdab.com>",
  "Gerhard de Clercq <gerhard.declercq@kdab.com>",
  "Leon Matthes <leon.matthes@kdab.com>"
]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cxx = "1.0.75"
# Use `cxx-qt = "0.4"` here instead!
cxx-qt = { path = "../../crates/cxx-qt" }
# Use `cxx-qt-lib = "0.4"` here instead!
cxx-qt-lib = { path = "../../crates/cxx-qt-lib" }

[build-dependencies]
# Use `cxx-qt-build = "0.4"` here instead!
cxx-qt-build = { path = "../../crates/cxx-qt-build" }
# ANCHOR_END: book_cargo_toml_no_cmake
