# SPDX-FileCopyrightText: 2021 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-FileContributor: Andrew Hayzen <andrew.hayzen@kdab.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
[package]
name = "cxx_qt_demo_threading"
version = "0.1.0"
authors = ["Andrew Hayzen <andrew.hayzen@kdab.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
async-std = { git = "https://github.com/async-rs/async-std.git", default-features = false, features = ["std"] }
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["full"] }
futures = "0.3"
futures-timer = "3.0"
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1.2", features = ["serde"] }

[build-dependencies]
cxx-qt-build.workspace = true

[features]
link_qt_object_files = [ "cxx-qt-build/link_qt_object_files" ]
