# SPDX-FileCopyrightText: 2021 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-FileContributor: Andrew Hayzen <andrew.hayzen@kdab.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[book]
authors = ["Andrew Hayzen <andrew.hayzen@kdab.com>"]
language = "en"
multilingual = false
src = "src"
title = "CXX-Qt Documentation"

[output.html]

[output.linkcheck]
optional = true
